[package]
name = "fastnote-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
ropey = { workspace = true }
pulldown-cmark = { workspace = true }
anyhow = { workspace = true }
smallvec = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
